package edu.odu.cs.cs350;

/**
 * 
 * TokenKind object
 * Stores token identifiers
 *
 */
public enum TokenKind {
	// keywords
	ABSTRACT, ALIGNAS, ALIGNOF, ASM, ATOMIC_CANCEL, ATOMIC_COMMIT, ATOMIC_NOEXCEPT, AUTO, 
	BITAND, BITOR, BOOL, BOOLEAN, BREAK, BYTE, CASE, CATCH, CHAR, CIN, CLASS, COMPL, COUT, 
	CONCEPT, CONST, CONSTEVAL, CONSTEXPR, CONST_CAST, CONTINUE, CO_AWAIT, CO_RETURN, CO_YIELD,  
	DECLTYPE, DEFAULT, DELETE, DO, DOUBLE, DYNAMIC_CAST, ELSE, ENUM, EXPLICIT, EXPORT, EXTERN, EXTENDS, 
	FINAL, FINALLY, FLOAT, FOR, FRIEND,	GOTO, IF, IMPLEMENTS, IMPORT, INLINE, INSTANCEOF, INT, INTERFACE,
	LONG, MUTABLE, NAMESPACE, NATIVE, NEW, NOEXCEPT, NULLPTR, OPERATOR,	PACKAGE, PRIVATE, PROTECTED, PUBLIC,
	REFLEXPR, REGISTER, REINTERPRET_CAST, REQUIRES, RETURN,	SHORT, SIGNED, SIZEOF, STATIC, STATIC_ASSERT, STATIC_CAST, 
	STRICTFP, STRING, STRUCT, SUPER, SWITCH, SYNCHRONIZED, TEMPLATE, THIS, THREAD_LOCAL, THROW, THROWS, TRANSIENT, TRY, 
	TYPEDEF, TYPEID, TYPENAME, UNION, UNSIGNED, USING, VIRTUAL, VOID, VOLATILE,	WCHART_T, WHILE,
	
	// containers
	ARRAY, BITSET, DEQUE, FORWARD_LIST, LIST, MAP, QUEUE, SET, STACK, UNORDERED_MAP, UNORDERED_SET, VECTOR,
	
	// IO Streams
	FSTREAM, IOMANIP, IOS, IOSFWD, IOSTREAM, ISTREAM, OSTREAM, SSTREAM, STREAMBUF,
	
	// General
	ALGORITHM, CHRONO, FUNCTIONAL, ITERATOR, MEMORY, STDEXCEPT, UTILITY,
	
	// boolean literals
	BOOLEANTRUE, BOOLEANFALSE,
	
	//null literal
	NULL_LITERAL,
	
	//separators
	LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK, SEMICOLON, COMMA, DOT,
	
	//operators
	EQ, GT, LT, NOT, COMP, QUESTION, COLON, EQEQ, LTEQ, GTEQ, NOTEQ, ANDAND, 
	OROR, PLUSPLUS, MINUSMINUS, PLUS, MINUS, MULT, DIV, AND, OR, XOR, MOD,
	LSHIFT, RSHIFT, URSHIFT, PLUSEQ, MINUSEQ, MULTEQ, DIVEQ, ANDEQ, OREQ,
	XOREQ, MODEQ, LSHIFTEQ, RSHIFTEQ, URSHIFTEQ, 
	
	//identifiers
	IDENTIFIER,
	
	//integers
	INTEGER_LITERAL, DEC_INTEGER_LITERAL,
	
	//end of file
	EOF
	
};
